module DataFoodConsortium
	module ConnectorV1
		require 'datafoodconsortium/connector_v1/connector'
		require 'datafoodconsortium/connector_v1/json_ld_serializer'
		require 'datafoodconsortium/connector_v1/skos_parser_element'
		require 'datafoodconsortium/connector_v1/skos_parser'
		require 'datafoodconsortium/connector_v1/agent.rb'
		require 'datafoodconsortium/connector_v1/customer_category.rb'
		require 'datafoodconsortium/connector_v1/enterprise.rb'
		require 'datafoodconsortium/connector_v1/person.rb'
		require 'datafoodconsortium/connector_v1/phone_number.rb'
		require 'datafoodconsortium/connector_v1/social_media.rb'
		require 'datafoodconsortium/connector_v1/address.rb'
		require 'datafoodconsortium/connector_v1/allergen_characteristic.rb'
		require 'datafoodconsortium/connector_v1/characteristic.rb'
		require 'datafoodconsortium/connector_v1/nutrient_characteristic.rb'
		require 'datafoodconsortium/connector_v1/physical_characteristic.rb'
		require 'datafoodconsortium/connector_v1/quantitative_value.rb'
		require 'datafoodconsortium/connector_v1/quantity.rb'
		require 'datafoodconsortium/connector_v1/defined_product.rb'
		require 'datafoodconsortium/connector_v1/flow.rb'
		require 'datafoodconsortium/connector_v1/localized_product.rb'
		require 'datafoodconsortium/connector_v1/physical_product.rb'
		require 'datafoodconsortium/connector_v1/planned_consumption_flow.rb'
		require 'datafoodconsortium/connector_v1/planned_local_consumption_flow.rb'
		require 'datafoodconsortium/connector_v1/planned_local_production_flow.rb'
		require 'datafoodconsortium/connector_v1/planned_local_transformation.rb'
		require 'datafoodconsortium/connector_v1/planned_production_flow.rb'
		require 'datafoodconsortium/connector_v1/planned_transformation.rb'
		require 'datafoodconsortium/connector_v1/realized_consumption_flow.rb'
		require 'datafoodconsortium/connector_v1/realized_production_flow.rb'
		require 'datafoodconsortium/connector_v1/realized_transformation.rb'
		require 'datafoodconsortium/connector_v1/supplied_product.rb'
		require 'datafoodconsortium/connector_v1/technical_product.rb'
		require 'datafoodconsortium/connector_v1/catalog.rb'
		require 'datafoodconsortium/connector_v1/catalog_item.rb'
		require 'datafoodconsortium/connector_v1/delivery_option.rb'
		require 'datafoodconsortium/connector_v1/offer.rb'
		require 'datafoodconsortium/connector_v1/order.rb'
		require 'datafoodconsortium/connector_v1/order_line.rb'
		require 'datafoodconsortium/connector_v1/payment_method.rb'
		require 'datafoodconsortium/connector_v1/physical_place.rb'
		require 'datafoodconsortium/connector_v1/pickup_option.rb'
		require 'datafoodconsortium/connector_v1/price.rb'
		require 'datafoodconsortium/connector_v1/product_batch.rb'
		require 'datafoodconsortium/connector_v1/real_stock.rb'
		require 'datafoodconsortium/connector_v1/sale_session.rb'
		require 'datafoodconsortium/connector_v1/shipping_option.rb'
		require 'datafoodconsortium/connector_v1/theoretical_stock.rb'
		require 'datafoodconsortium/connector_v1/virtual_place.rb'
		require 'datafoodconsortium/connector_v1/skos_concept.rb'

		def self.semantic_types
		  constants.map(&method(:const_get)).select do |c|
		    c.constants.include?(:SEMANTIC_TYPE)
		  end
		end
	end
end
